apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort      
  selector:
    app: mysql      
  ports:
    - protocol: TCP 
      port: 3306
      nodePort: 30036
      targetPort: 3306
      #clusterIP: 10.106.251.123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: pass123
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /media/vu2hsj/Z/mysqldata/
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
